### ISSUE TITLE
run on VS2019 or 2022

### ISSUE THREAD

**Issue by emplant2000** [louangr/VISCACameraController#1]
Hi

Let me try to publish on 2019.

to be an error.

Value TargetFramework  'net6.0-windows10.0.19041.0' is not defined.

Any idea?

**Comment by louangr** [comment]
Hi,

Personally, I'm using VS2022, but I think it might be possible with VS2019.

Yes, you need to install this specified SDK.
For that :
- open Visual Studio Installer
- click 'Modify' in the VS2019 (or 2022) section
- if you haven't done so yet, check the '.NET desktop development' and 'Universal Windows Platform development' packages
- check 'Windows 11 SDK (10.0.22621.0)' and 'Windows 10 SDK (10.0.19041.0)' SDKs
![image](https://github.com/louangr/VISCACameraController/assets/60884886/640d2292-1326-4b80-93cb-bcf93454ea15)
- install all this
- then, restart your VS2019 (or 2022) and run the project

Hope this was helpful!

**Comment by emplant2000** [comment]
Hi

Installed specified Win10 and Win11 SDK.

and running on VS 2019. I got these warn and errs.
Any idea?

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The element 'PropertyGroup' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003' has invalid child element 'PathToXAMLWinRTImplementations' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003'. List of possible elements expected: 'Property, VisualStudioVersion, MinimumVisualStudioVersion, AdditionalFileItemNames, AllowUnsafeBlocks, AnalysisMode, AppConfigForCompiler, ApplicationIcon, ApplicationRevision, ApplicationVersion, AppDesignerFolder, AspNetConfiguration, AspNetCoreHostingModel, AspNetCoreModuleName, AssemblyKeyContainerName, AssemblyKeyProviderName, AssemblyName, AssemblyOriginatorKeyFile, AssemblyOriginatorKeyFileType, AssemblyOriginatorKeyMode, AssemblyType, AutoGenerateBindingRedirects, AutorunEnabled, BaseAddress, BootstrapperComponentsLocation, BootstrapperComponentsUrl, BootstrapperEnabled, CharacterSet, CheckForOverflowUnderflow, CLRSupport, UseDebugLibraries, CodePage, Configuration, ConfigurationName, ConfigurationOverrideFile, CreateDesktopShortcut, CreateWebPageOnPublish, CurrentSolutionConfigurationContents, DebugSecurityZoneURL, DebugSymbols, DebugType, DefaultClientScript, DefaultHTMLPageLayout, DefaultTargetSchema, DefineConstants, DefineDebug, DefineTrace, DelaySign, DisableLangXtns, DisallowUrlActivation, ....	VISCACameraController (Package)	C:\Users\mack\Source\Repos\VISCACameraController\VISCACameraController (Package)\VISCACameraController (Package).wapproj	34	


Severity	Code	Description	Project	File	Line	Suppression State
Warning		The element 'PropertyGroup' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003' has invalid child element 'PackageCertificateThumbprint' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003'. List of possible elements expected: 'Property, VisualStudioVersion, MinimumVisualStudioVersion, AdditionalFileItemNames, AllowUnsafeBlocks, AnalysisMode, AppConfigForCompiler, ApplicationIcon, ApplicationRevision, ApplicationVersion, AppDesignerFolder, AspNetConfiguration, AspNetCoreHostingModel, AspNetCoreModuleName, AssemblyKeyContainerName, AssemblyKeyProviderName, AssemblyName, AssemblyOriginatorKeyFile, AssemblyOriginatorKeyFileType, AssemblyOriginatorKeyMode, AssemblyType, AutoGenerateBindingRedirects, AutorunEnabled, BaseAddress, BootstrapperComponentsLocation, BootstrapperComponentsUrl, BootstrapperEnabled, CharacterSet, CheckForOverflowUnderflow, CLRSupport, UseDebugLibraries, CodePage, Configuration, ConfigurationName, ConfigurationOverrideFile, CreateDesktopShortcut, CreateWebPageOnPublish, CurrentSolutionConfigurationContents, DebugSecurityZoneURL, DebugSymbols, DebugType, DefaultClientScript, DefaultHTMLPageLayout, DefaultTargetSchema, DefineConstants, DefineDebug, DefineTrace, DelaySign, DisableLangXtns, DisallowUrlActivation, ....	VISCACameraController (Package)	C:\Users\mack\Source\Repos\VISCACameraController\VISCACameraController (Package)\VISCACameraController (Package).wapproj	44	


Severity	Code	Description	Project	File	Line	Suppression State
Warning		The element 'ProjectReference' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003' has invalid child element 'SkipGetTargetFrameworkProperties' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003'. List of possible elements expected: 'Name, Project, ReferenceOutputAssembly, SpecificVersion, Targets, OutputItemType, Package, EmbedInteropTypes, IncludeAssets, ExcludeAssets, PrivateAssets' in namespace 'http://schemas.microsoft.com/developer/msbuild/2003'.	VISCACameraController (Package)	C:\Users\mack\Source\Repos\VISCACameraController\VISCACameraController (Package)\VISCACameraController (Package).wapproj	142	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.	VISCACameraController	C:\Program Files\dotnet\sdk\5.0.416\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	141

**Comment by emplant2000** [comment]
Hi

I got it on VS2022 with only Win10 SDK and specified 'Project Propety(package)' 

Target Version 19041 as ok :)

too much thanks.

![hW9Y4WvqAC](https://github.com/louangr/VISCACameraController/assets/721686/28aa7e43-5cbb-4dfb-a561-d5fff5403533)
