### ISSUE TITLE
Mult-Device option?

### ISSUE THREAD

**Issue by TheTinkererGuy** [louangr/VISCACameraController#3]
Hello
This isn't really an issue but a question, does this support multiple devices that can accept Visca or just one?.
Basically daisy chain of multiple Visca enabled devices?.
Thanks

**Comment by louangr** [comment]
Hi,

The VISCA protocol can manage up to 7 devices on the same serial communication (➡️ this [document](https://www.sony.net/Products/CameraSystem/CA/BRC_X1000_BRC_H800/Technical_Document/C456100121.pdf) p.3). But this app doesn't support it, sorry 😓

This means you can add this feature to this app or develop your own app based on this one 💻

Esle, if you have for example 2 devices to manage. You can connect these 2 devices independently to your computer (1 serial communication per device) and open this application twice but, by selecting the 2 differents COM port, target the 2 devices. 

Hope this was helpful!
